### ISSUE TITLE
Name suggestions

### ISSUE THREAD

**Issue by ryfactor** [delta-lang/delta#1]
How about "_Schwa_"? https://en.wikipedia.org/wiki/Schwa

Never been used before, and it has a cute symbol

**Comment by emillaine** [comment]
Thanks for the suggestion! I like that it's short, but I think it might be a little too "exotic". Probably because of the four adjacent consonants. In my opinion, the name should be more familiar to English speakers, so that e.g. you know how to spell it when you hear it, etc.

**Comment by emillaine** [comment]
Closing this for now since this isn't a current priority.
