### ISSUE TITLE
Create separate site for stdlib api reference

### ISSUE THREAD

**Issue by Coolnesss** [delta-lang/delta#17]
For easy reference to stdlib functions and classes

- [x] Matching header bar for main page, API reference site, and sandbox.
- [x]  Host on GitHub Pages. ~Hosted on [surge.sh](https://delta-lang.surge.sh).~

**Comment by Coolnesss** [comment]
MVP: Create front-end site that parses documentation on page load and produces nice format

**Comment by emillaine** [comment]
Matching header bar and hosting on GitHub Pages now implemented in https://github.com/delta-lang/delta-lang.github.io.
