### ISSUE TITLE
Initialize Array with array literal

### ISSUE THREAD

**Issue by Coolnesss** [delta-lang/delta#33]
E.g

```swift
var a = Array([1,2,3,4]);
```

Note also no generics type needed, since it can be determined from the type of the array given to the constructor

**Comment by emillaine** [comment]
You can now use one of the following:

```swift
var a = Array(&[1,2,3,4]);
```

or 

```swift
var a = Array<int>([1,2,3,4]);
```

Once generic argument inference and auto-referencing work together we can have ```Array([1,2,3,4])```.
