### ISSUE TITLE
Why delta instead of C++/Rust?

### ISSUE THREAD

**Issue by lausek** [delta-lang/delta#44]
Adding a short explanation to the docs about why one would use delta instead of C++/Rust, should be considered. At this moment it only tells us, that delta should be seen as a replacement for C++, but what does it do better then?

**Comment by emillaine** [comment]
Thanks for pointing this out, this is definitely an important thing to have. I'll write it tomorrow.

**Comment by emillaine** [comment]
@lausek I wrote a list of things that Delta is supposed to do better than C++ and Rust in #45. Does it match what you were looking for, or is there something I should explain more?

**Comment by lausek** [comment]
@emlai Pretty good, keep it up 👍

**Comment by emillaine** [comment]
@lausek Great! Thanks again.
