### ISSUE TITLE
support for musl libc

### ISSUE THREAD

**Issue by aifoslinux** [delta-lang/delta#48]
Musl libc doesn't have libexecinfo support which is why there is error at compile time:

> /tmp/delta-991067.o: In function `printStackTrace':
:(.text+0x2146): undefined reference to `backtrace'
:(.text+0x2154): undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status

I've disabled[1] some lines in stdlib/os/gnu.delta by commenting some lines and compiling works on musl libc. I was wondering if it would be better to  have support for both glibc or musl by ifdefs or something like that?

1:

> //extern func backtrace(array: mutable void mutable**, size: int) -> int;
> //extern func backtrace_symbols(array: mutable void**, size: int) -> mutable char mutable**?;
> 
> func printStackTrace() {
>     //var callstack: mutable void*[128] = undefined;
> 
>     //let frames = backtrace(&callstack[0], int(callstack.size()));
>     //let strings = backtrace_symbols(&callstack[0], frames);
> 
>     //if (strings == null) {
>     //    return;
>     //}
> 
>     //for (let i in 0..frames) {
>     //    printf("%s\n", *(strings! + i));
>     //}
> 
>     //free(cast<mutable void*>(strings!));
> }
> 
> func setAbortBehavior() {

**Comment by emillaine** [comment]
Yes, this will be possible once the equivalent of ifdefs is added to the language.

**Comment by emillaine** [comment]
@aifoslinux Commit 0ac188e159145c46f13ff74180ea505230c08dfa should fix this by ifdefing the backtrace code out if execinfo.h is not found. Thanks for reporting!

**Comment by aifoslinux** [comment]
I've tested the commit and it works fine, thanks!
