### ISSUE TITLE
Windows does not has c++17

### ISSUE THREAD

**Issue by ghost** [delta-lang/delta#63]
@emlai 

Windows does not has c++17

**Comment by emillaine** [comment]
I have tested with Visual Studio 2019 and it has all the C++17 features that the project requires.

Though you're right Visual Studio still doesn't seem to have full C++17 support.

**Comment by ghost** [comment]
@emlai How to read user input in Delta? I mean something like `cin >>`.

**Comment by emillaine** [comment]
Using [`readLine()`](https://github.com/delta-lang/delta/blob/a5b03bf3a9b9d4f98c14053196811e941bb56d0d/std/stdio.delta#L68):

    var line = readLine()

**Comment by ghost** [comment]
@emlai Thanks. 
Also I have last question about Delta. I noticed that Delta is very similar to C, what advantages does Delta have over C? Or just Delta features

**Comment by emillaine** [comment]
Sorry took a while to respond. The introduction chapter in the documentation explains the differences and additional features compared to C quite thoroughly: https://delta-lang.github.io/introduction.html. Hope it helps.
