### ISSUE TITLE
documentation examples that throws error

### ISSUE THREAD

**Issue by ghost** [delta-lang/delta#73]
I stumbled upon some issues with the examples in the documentation. There errors are found in the function section:

> 
> main.cx:1:16: error: expected ',', got '='
> void foo(int i = 0) {
>                ^

> main.cx:6:9: error: expected identifier, got '('
>     var (i, b) = foo();
>         ^

I get error with array reference example as well:

> Assertion failed: left->getType()->equals(right->getType()) (/ev/.cx/src/backend/irgen.h: createBinaryOp: 146)
> Please submit a bug report to https://github.com/cx-language/cx/issues and include the crash backtrace.
> Stack dump:
> 0.	Program arguments: cx array.cx
> zsh: abort      cx array.cx

Map, filter example htrows this error:

> 
> array.cx:8:31: error: invalid argument #1 type 'bool(int)' to 'List<int>.filter', expected 'bool(int*)'
>     var even = numbers.filter(isEven);
>                                        ^
> 

Pointers example gives this error:

> pointers.cx:14:15: error: unknown identifier '*'
>     println(p * q); // Multiplies the values pointed to by p and q, prints 42
>                 ^

Nullable types has these errors:

```
nullable.cx:17:23: error: no matching operator '+' with arguments 'int?' and 'int'
        int bar = foo + 1;
                      ^
/ev/.cx/std/StringBuffer.cx:199:14: note: candidate function:
StringBuffer operator+(string a, string b) {
             ^
/ev/.cx/std/StringBuffer.cx:213:14: note: candidate function:
StringBuffer operator+(string a, char b) {
             ^
/ev/.cx/std/StringBuffer.cx:217:14: note: candidate function:
StringBuffer operator+(string a, char[*] b) {
             ^
/ev/.cx/std/StringBuffer.cx:221:14: note: candidate function:
StringBuffer operator+(StringBuffer a, string b) {
             ^
/ev/.cx/std/StringBuffer.cx:231:14: note: candidate function:
StringBuffer operator+(StringBuffer a, char b) {
             ^
/ev/.cx/std/StringBuffer.cx:237:14: note: candidate function:
StringBuffer operator+(StringBuffer a, char[*] b) {
             ^

```

Non-null assertion operator:

> Assertion failed: Val && "isa<> used on a null pointer" (/usr/include/llvm/Support/Casting.h: doit: 104)
> Please submit a bug report to https://github.com/cx-language/cx/issues and include the crash backtrace.
> Stack dump:
> 0.	Program arguments: cx nullable.cx
> zsh: abort      cx nullable.cx

**Comment by emillaine** [comment]
Thanks! The examples in the documentation are not yet automatically tested, so breakage like this can happen. Also some of the examples featured unimplemented features. I have now removed the examples about unimplemented features, and fixed most of the other bugs. Still have to fix the last two. I'm also back to work from vacation so not sure when I have time to work on this.

**Comment by emillaine** [comment]
All documentation example codes have been fixed now.
