### ISSUE TITLE
Question: What is relation between this language and the one mentioned on Wikipedia?

### ISSUE THREAD

**Issue by rzuckerm** [delta-lang/delta#77]
I'm one of the maintainers of the [Sample Programs](https://github.com/TheRenegadeCoder/sample-programs), and I've been trying to find or create docker images for the different languages that are currently untested. I stumbled upon this repo and went to the trouble of creating a [docker image](https://hub.docker.com/r/rzuckerm/c-star). Here is the [Dockerfile](https://github.com/rzuckerm/c-star-docker-image/blob/main/Dockerfile) if you're curious.

While looking for information on this language, I saw [this Wikipedia Article](https://en.wikipedia.org/wiki/C*) and found this [User Guide](http://people.csail.mit.edu/bradley/cm5docs/CM-5CStarUsersGuide.pdf) from the now defunct company Thinking Machines. I'm just curious if this is in any way based on that version of C\* or if it is a completely new language that just happens to have the same name. The reason why I'm asking is that I'd like to update these articles on the [Sample Programs companion website](https://sampleprograms.io/) as a result of [this PR](https://github.com/TheRenegadeCoder/sample-programs/pull/3570):

- [The C* Programming Language](https://sampleprograms.io/languages/c-star/)
- [Hello World in C*](https://sampleprograms.io/projects/hello-world/c-star/)

**Comment by emillaine** [comment]
Hello @rzuckerm! Yes, this is a new language, and completely unrelated to the old C* that's on Wikipedia.

And thanks for the Docker image! It might come in handy, though I'm not working on this project for the foreseeable future.

**Comment by rzuckerm** [comment]
Thanks @emlai , you answered my question. I'll close this issue.

@jrg94 FYI
