### ISSUE TITLE
let keyword is broken

### ISSUE THREAD

**Issue by cxcorp** [delta-lang/delta#9]
Minimal example in the [sandbox](https://delta-lang.github.io/delta-sandbox/):

```javascript
import "stdio.h"

func main() {
    let bar = "foo"
    //  ^ unexpected identifier
}
```

**Comment by emillaine** [comment]
Thanks! [delta-sandbox](https://github.com/delta-lang/delta-sandbox) wasn't using an up-to-date version of Delta so it didn't know of `let`. This specific bug is now fixed but there are other bugs that currently prevent compilation in the sandbox.
